### PR TITLE
Add Bootstrap Website

### PR DESCRIPTION
**Pull request by harsitagarwalla187**

### CODE REVIEW

**Review by Diptonil — CHANGES_REQUESTED** [review]
Good work, @harsitagarwalla187.
- Just lowercase the name of `Bootstrap.html` (HTML source files are generally lowercase and, if needed, separated by hyphens (in conjunction with SEO standards). Preferably, the file name should be `index.html`.
- Change the folder name of your website from `Bootstrap Website` into something else that is identifiable with your work (like `Burger House` or something).
- Please remove all the dead space between the script tags and the end of the head tag. Remove unnecessary blank lines wherever applicable.

**Comment by harsitagarwalla187** [comment]
Ok

**Review by Diptonil — APPROVED** [review]
Looks good. Your PR would be merged soon.

**Comment by harsitagarwalla187** [comment]
Ok, Thank You.

**Pull request merged**
